let name = prompt('What your name ?').toUpperCase()
let lowName = name.toLowerCase()
let tamanho = name.length
let ultimo = name.charAt( name.length - 1);
let tresUltimas =  name.slice (-3)
let indiceLetraF = name.indexOf('F')
document.body.innerHTML += `Seu nome e ${name} <br/>`
document.body.innerHTML += `seu nome tem ${tamanho} letras <br/>`
document.body.innerHTML += `A segunda letra do seu nome é <strong>${name[1]}</strong><br>`
document.body.innerHTML += `O primeiro índice da letra F no seu nome? ${indiceLetraF}<br>`
document.body.innerHTML += `O último índice da letra LETRA no seu nome? ${ultimo} <br>`
document.body.innerHTML += `As últimas 3 letras do seu nome são:${tresUltimas}<br>`
document.body.innerHTML += `As palavras do seu nome são: ${name.split(' ')}<br>`
document.body.innerHTML += `Seu nome com letras maiúsculas: ${name} <br>`
document.body.innerHTML += `Seu nome com letras minúsculas: ${lowName}`